In [1]:
import numpy as np
np.random.seed(0)

### check the shape of a matrix

In [12]:
A = np.arange(9).reshape(3,3)
A


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
b = np.ones((3,1))
b

array([[1.],
       [1.],
       [1.]])

In [7]:
C = np.hstack((b,A))
C

array([[1., 0., 1., 2.],
       [1., 3., 4., 5.],
       [1., 6., 7., 8.]])

In [18]:
C.shape

3

### 1D array VS 2D array

In [8]:
a = np.array([1,2,3])
b = np.array([[1,2,3]])

In [9]:
print(a.shape)
print(b.shape)

(3,)
(1, 3)


In [11]:
b1 = b.flatten()
print(b1.shape)
a1 = a[:,np.newaxis]
print(a1.shape)

(3,)
(3, 1)


### vectorization ------white board example

This notebook is for showing the different operations that can be performed using Numpy - a fundamental package for scientific computing with Python.

## Contents

+ <a href='#section_1'>Array Creation</a>
    - <a href='#section_1.1'>Rank-1 (1D) array [np.array(), np.random.randn(), np.random.randint(), np.arange()] </a>
    - <a href='#section_1.2'>Rank-2 (2D) array [np.array(), np.random.rand(), np.random.random(), np.random.randn(), random.randint(), np.arange(), np.zeros(), np.ones(), np.full(), np.empty(), np.arange().reshape()] </a>
+ <a href='#section_2'>Array Indexing</a>
    - <a href='#section_2.1'>Basics</a>
    - <a href='#section_2.2'>np.tril_indices</a>
    - <a href='#section_2.3'>np.triu_indices</a>
+ <a href='#section_3'>Broadcasting</a>
+ <a href='#section_4'>Array Arithmetic </a>
    - <a href='#section_4.1'>Elementwise operations on arrays [np.add(), np.subtract(), np.multiply(), np.divide(), np.sqrt(), np.sum(), np.diff(), np.mean(), np.log()]</a>
    - <a href='#section_4.2'>Matrix-Matrix and Matrix-Vector multiplication [np.dot()]</a>
    - <a href='#section_4.3'>Computation on arrays [np.sum(), np.transpose(), np.diff(), np.mean()]</a>
    - <a href='#section_4.4'>Padding [np.pad()]</a>
    - <a href='#section_4.5'>Clipping elements of an array [clip()]</a>
    - <a href='#section_4.6'>Flattening of an array [ravel(), reshape(), flatten(), flat()]</a>
    - <a href='#section_4.7'>any() vs all()</a>
    - <a href='#section_4.8'>Array Manipulation [vstack(), hstack()]</a>
+ <a href='#section_5'>Constants [np.inf, np.nan]</a>
+ <a href='#section_6'>Linear algebra [np.linalg.det, np.linalg.solve, np.linalg.pinv, np.linalg.inv, np.linalg.eig, np.linalg.svd]</a>

In [1]:
import numpy as np
np.random.seed(0)

<a id="section_1"></a>

## Array Creation

Array creation in numpy is pretty useful in almost every scientific computation.

<a id="section_1.1"></a>

### Rank-1 (1D) array

`numpy.random.random` is actually an alias for `numpy.random.random_sample`

With `numpy.random.rand`, the shapes of the output array are separate arguments. With `numpy.random.random_sample`, the shape argument is a single tuple.

In [3]:
#Creates a rank-1 array (1D array) -> neither a row vector or column vector
v1 = np.array([1, 0, 1])
print(v1)        # [1,0,1]
print(v1.shape)  # (3,)

#Create a rank-1 array (1D array) (rank is the number of dimensions) 
print()
arr1 = np.array([1,2,3])
#Getting the class of created array
print(type(arr1))  # <class 'numpy.ndarray'>

#Creates a rank-1 array of five random gaussian variables
print()
print(np.random.randn(5))   # [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]

#Create a rank-1 array of random integers between 0 and 1, inclusive 
print()
print(np.random.randint(5,10, size=10))  # [1 1 1 1 1 0 1 1 0 0]

#Create a rank-1 array of random integers between 0 and 1, exclusive
print()
print(np.random.randint(1, size=10))  # [0 0 0 0 0 0 0 0 0 0]

#Another way to create rank-1 array with sequence of numbers
print()
print(np.arange(8))   # [0 1 2 3 4 5 6 7]

[1 0 1]
(3,)

<class 'numpy.ndarray'>

[-0.97727788  0.44386323  0.33367433  1.49407907 -0.20515826]

[0 1 0 1 1 1 1 0 1 0]

[0 0 0 0 0 0 0 0 0 0]

[0 1 2 3 4 5 6 7]


<a id="section_1.2"></a>

### Rank-2 (2D) array

In [13]:
#Creates column vector (many rows, one column) -> [[e1], [e2], [e3]]
print()
v2 = np.array([[1], [0], [1]])
print(v2.shape)  # (1,3)

#Getting number of rows of an array
print()
print(v2.shape[0]) # 3

#Getting number of columns of columns of an array
print()
print(v2.shape[1]) # 1

#Creates array (3x4) of random numbers with size 3 rows and 4 columns 
arr1 = np.random.rand(3,4)
print(arr1)  # [[ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318],
             #  [ 0.4236548 ,  0.64589411,  0.43758721,  0.891773  ],
             #  [ 0.96366276,  0.38344152,  0.79172504,  0.52889492]]


#Creates array (2x2) with random values
print()
rand_array = np.random.random((2,2))
print(rand_array)  # [[ 0.56804456  0.92559664]
                   #  [ 0.07103606  0.0871293 ]]

       
#Creates array (3x4) with random values
print() 
rand_array = np.random.random((3,4))
print(rand_array)  # [[ 0.0202184   0.83261985  0.77815675  0.87001215]
                   #  [ 0.97861834  0.79915856  0.46147936  0.78052918]
                   #  [ 0.11827443  0.63992102  0.14335329  0.94466892]]


#Creates 2x4 array of samples from N(3, 6.25)
print(2.5 * np.random.randn(2, 4) + 3)  # [[ 0.30430499  6.48868068  7.46871011  1.57620684]
                                        #  [ 3.43846633  1.84373615  0.28549851  4.59933999]]


#Creates 2x4 array of ints between 0 and 4, inclusive
print()
print(np.random.randint(5, size=(2, 4)))  # [[3 0 3 4]
                                          #  [1 2 4 3]]


#Creates rank-2 array (3x4) (2D array) -> [[row0],[row1],[row2]]
print()
arr2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr2)  #  [[ 1  2  3  4]
             #   [ 5  6  7  8]
             #   [ 9 10 11 12]]

#Creates array (3x4) of zeros 
print()
x_zeros = np.zeros((2,2))
print(x_zeros)  # [[ 0.  0.]
                #  [ 0.  0.]]

#Creates array (2x2) of ones
print()
x_ones = np.ones((2,2))
print(x_ones)   # [[ 1.  1.]
                #  [ 1.  1.]]

#Creates constant array (2x2) of a specified value
print()
cons = np.full((2,2), 5)
print(cons)   # [[5 5]
              #  [5 5]]



#creates new array of zeros/ones like the shape and type of input array
print()
x = np.arange(6).reshape((2, 3))
print(x)  # [[0 1 2]
          #  [3 4 5]]
print()
print(np.zeros_like(x))  # [[0 0 0]
                         #  [0 0 0]]
print()
print(np.ones_like(x)) # [[1 1 1]
                       #  [1 1 1]]   
    
#Creates identity matrix (2x2)
print()
ident = np.eye(2)

print()
print(ident)  # [[ 1.  0.]
              #  [ 0.  1.]]
    
diag = np.diag([1,2,3])
print(diag)  #[[1 0 0]
             #[0 2 0]
             #[0 0 3]]


#Method to create a 2D array from 1D (rank-1) array
print()
print(np.arange(8).reshape(4,2))   # [[0 1]
                                   #  [2 3]
                                   #  [4 5]
                                   #  [6 7]]


(3, 1)

3

1
[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]]

[[0.56804456 0.92559664]
 [0.07103606 0.0871293 ]]

[[0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892]]
[[-3.38247454  4.63404649  5.1610905   1.14458745]
 [ 8.67438656 -0.63591419  3.11439629  2.53204037]]

[[0 4 1 4]
 [1 2 2 0]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]]

[[5 5]
 [5 5]]

[[0 1 2]
 [3 4 5]]

[[0 0 0]
 [0 0 0]]

[[1 1 1]
 [1 1 1]]


[[1. 0.]
 [0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


<a id="section_2"></a>

## Array indexing

<a id="section_2.1"></a>

### Basics

In [16]:
#Creates an rank-2 array (2D array) -> [[row0],[row1],[row2]]
arr2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr2)    # [[ 1  2  3  4]
               #  [ 5  6  7  8]
               #  [ 9 10 11 12]]

arr2[[0,1,2],[1,2,1]] = 999
arr2


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[  1, 999,   3,   4],
       [  5,   6, 999,   8],
       [  9, 999,  11,  12]])

In [6]:

a = np.arange(16).reshape(4, 4)
print(a) # [[ 0  1  2  3]
         #  [ 4  5  6  7]
         #  [ 8  9 10 11]
         #  [12 13 14 15]]

print()

# Compute two different sets of indices to access 4x4 arrays, one for the lower triangular part starting at the main diagonal
il1 = np.tril_indices(4)
print(il1)


# and one starting two diagonals further right:
il2 = np.tril_indices(4, k = 2)
print(il2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

(array([0, 1, 1, 2, 2, 2, 3, 3, 3, 3]), array([0, 0, 1, 0, 1, 2, 0, 1, 2, 3]))

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]), array([0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [7]:
# for indexing
print(a[il1])


print(a[il2])

[ 0  4  5  8  9 10 12 13 14 15]

[ 0  1  2  4  5  6  7  8  9 10 11 12 13 14 15]


In [53]:
# for assigning values
a[il1] = -1
print(a)

[[-1  1  2  3]
 [-1 -1  6  7]
 [-1 -1 -1 11]
 [-1 -1 -1 -1]]


<a id="section_2.3"></a>

See [np.triu_indices()](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.triu_indices.html#numpy.triu_indices)

Return the indices for the upper-triangle of an (n, m) array

In [54]:
a = np.arange(16).reshape(4, 4)
print(a)
print()

# Compute two different sets of indices to access 4x4 arrays, one for the upper triangular part starting at the main diagonal,
iu1 = np.triu_indices(4)
print(iu1)
print()

# and one starting two diagonals further right:
iu2 = np.triu_indices(4, k = 2)
print(iu2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

(array([0, 0, 0, 0, 1, 1, 1, 2, 2, 3]), array([0, 1, 2, 3, 1, 2, 3, 2, 3, 3]))

(array([0, 0, 1]), array([2, 3, 3]))


In [55]:
# Both for indexing
print(a[iu1])
print()

# And for assigning values
a[iu1] = -1
print(a)

[ 0  1  2  3  5  6  7 10 11 15]

[[-1 -1 -1 -1]
 [ 4 -1 -1 -1]
 [ 8  9 -1 -1]
 [12 13 14 -1]]


<a id="section_3"></a>

## Broadcasting

Broadcasting is a mechanism provided by numpy that allows to perform arithmetic operations with arrays of different shapes.

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [12]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
vec = np.array([1, 0, 1])
y = arr + vec  # Add vec to each row of arr using broadcasting
print(arr)
print()
print(y) # [[ 2  2  4]
         #  [ 5  5  7]
         #  [ 8  8 10]
         #  [11 11 13]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


<a id="section_4"></a>

## Array arithmetic

<a id="section_4.1"></a>

### Elementwise operations on arrays

In [13]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
print(x) # [[ 1.  2.]
         #  [ 3.  4.]]

y = np.array([[5,6],[7,8]], dtype=np.float64)
print(y)  # [[ 5.  6.]
          # [ 7.  8.]]

#Elementwise sum
print()
print(np.add(x,y))  #same as -> x + y    # [[  6.   8.]
                                         #  [ 10.  12.]]

#Elementwise substraction
print()
print(np.subtract(x, y)) #same as -> x - y  # [[-4. -4.]
                                            #  [-4. -4.]]

#Elementwise multiplication
print()
print(np.multiply(x, y)) #same as -> x * y  # [[  5.  12.]
                                            #  [ 21.  32.]]

#Elementwise division
print()
print(np.divide(x,y))  #same as -> x / y   # [[ 0.2         0.33333333]
                                           #  [ 0.42857143  0.5       ]]

#Elementwise square root
print()
print(np.sqrt(x))   # [[ 1.          1.41421356]
                    #  [ 1.73205081  2.        ]]

print()

#Elementwise natural log (base-e)
print(np.log(x))  # [[ 0.          0.69314718]
                  #  [ 1.09861229  1.38629436]]
    
print()

#Elementwise natural log of one plus the input array
print(np.log1p(x))  #[[ 0.69314718  1.09861229]
                    # [ 1.38629436  1.60943791]]
print()

# Elementwise exponential 
print(np.exp(x))

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]

[[ 6.  8.]
 [10. 12.]]

[[-4. -4.]
 [-4. -4.]]

[[ 5. 12.]
 [21. 32.]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[1.         1.41421356]
 [1.73205081 2.        ]]

[[0.         0.69314718]
 [1.09861229 1.38629436]]

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


<a id="section_4.2"></a>

### Matrix-Matrix  and Matrix-Vector multiplication

In [58]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
print(np.dot(a,b))  #np.dot is used for matrix-vector multilplication  # [[37 40]
                                                                       #  [85 92]]
    
print()    
a = np.array([[ 5, 1 ,3], 
              [ 1, 1 ,1], 
              [ 1, 2 ,1]])
b = np.array([1, 2, 3])
print(np.dot(a,b)) #np.dot is used for matrix-vector multilplication   # [16  6  8]

[[37 40]
 [85 92]]

[16  6  8]


<a id="section_4.3"></a>

### Computation on arrays

In [59]:
x = np.array([[1,2],[3,4]])
print(x)  # [[1 2]
          #  [3 4]]

#Sum of all elements of an array
print()
print(np.sum(x)) # 10

#Sum of all columns of an array
print()
print(np.sum(x, axis=0))  # [4 6]

#Sum of all rows of an array
print()
print(np.sum(x, axis=1))  # [3 7]

#Transpose of a matrix
print()
print(x.T)   # [[1 3]
             #  [2 4]]

print()
print(np.transpose(x))  # [[1 3]
                        # [2 4]]
    
#Calculate the n-th discrete difference along the given axis
x = np.array([1, 2, 4, 7, 0])
print()
print(np.diff(x)) # [ 1  2  3 -7]

print()
print(np.diff(x, n=2)) # [  1   1 -10]
print()

#Compute the arithmetic mean along the specified axis
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)   # [[1 2 3]
           #  [4 5 6]
           #  [7 8 9]]
print()

# Computing mean along the columns
print(x.mean(axis = 0))  # [12 15 18]

print()

# Computing mean along the rows
print(x.mean(axis = 1)) # [ 6 15 24]

[[1 2]
 [3 4]]

10

[4 6]

[3 7]

[[1 3]
 [2 4]]

[[1 3]
 [2 4]]

[ 1  2  3 -7]

[  1   1 -10]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[ 4.  5.  6.]

[ 2.  5.  8.]


<a id="section_4.4"></a>

### Padding

See [np.pad()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html)

In [60]:
### Rank-1 array
a = np.array([1, 2, 3, 4, 5])

In [61]:
np.pad(a, (2, 3), 'constant', constant_values=(4, 6))

array([4, 4, 1, 2, 3, 4, 5, 6, 6, 6])

In [62]:
np.pad(a, (2, 3), 'edge')

array([1, 1, 1, 2, 3, 4, 5, 5, 5, 5])

In [63]:
### Rank-2 array
a = np.array([[1, 2], [3, 4]])

In [64]:
np.pad(a, ((3, 2), (2, 3)), 'minimum')

array([[1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 2, 1, 1, 1],
       [3, 3, 3, 4, 3, 3, 3],
       [1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 2, 1, 1, 1]])

<a id="section_4.5"></a>

### Clipping elements of an array

See [np.clip()](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.clip.html)

In [65]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Clips (limits) the values in ** array a** between intervals **min (=1)** and **max (=8)** and place the **output array** in **a**

In [66]:
np.clip(a, 1, 8, out=a)

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

<a id="section_4.6"></a>

### Flattening of an array

In [67]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

See [np.ravel()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ravel.html)

In [68]:
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

See [np.reshape()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html#numpy.reshape)

In [69]:
#Equivalently, we can also write
x.reshape(-1)

array([1, 2, 3, 4, 5, 6])

See [np.flatten()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html#numpy.ndarray.flatten)

See [np.flat()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flat.html#numpy.ndarray.flat)

In [70]:
#np.flatten() in row major..can include ("C") as option, which is default
x.flatten()

array([1, 2, 3, 4, 5, 6])

In [71]:
#np.flatten() in column major
x.flatten("F")

array([1, 4, 2, 5, 3, 6])

<a id="section_4.7"></a>

### any() vs all()

In [72]:
#Test whether any array element along a given axis evaluates to True.
np.any([[True, False], [True, True]])

True

In [73]:
#Test whether all the elements along the column axis(axis=0) evaluates to True
np.all([[True,False],[True,True]], axis=0)

array([ True, False], dtype=bool)

In [1]:
all(x > 2 for x in [2, 0, 1, 5])

False

In [75]:
lst = [20, 300 , 50, -10, 60]
all(np.abs(np.diff(lst)) < 500)

True

<a id="section_4.8"></a>

### Array Manipulation

In [76]:
#Stack arrays in sequence vertically (row wise)

a = np.array([1, 2, 3]) # rank-1 array (3, )
b = np.array([2, 3, 4]) # rank-1 array (3, )
c = np.array([3, 4, 5]) # rank-1 array (3, )
res = np.vstack((a,b,c))  

print(res)  # [[1 2 3]
            #  [2 3 4]]
            #  [3 4 5]]


print()

print(np.vstack((a,b,c))[1:,:]) # Get the array of all the rows except the first row  # [[2 3 4]
                                                                                      #  [3 4 5]]
print()

print(np.vstack((a,b,c))[0,:]) # Get the first row as an array  # [1 2 3]
print()

a = np.array([[1], [2], [3]]) # rank-2 array (3, 1)
b = np.array([[2], [3], [4]]) # rank-2 array (3, 1)
print(np.vstack((a,b)))  # [[1]
                         #  [2]
                         #  [3]
                         #  [2]
                         #  [3]
                         #  [4]]

[[1 2 3]
 [2 3 4]
 [3 4 5]]

[[2 3 4]
 [3 4 5]]

[1 2 3]

[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


In [77]:
#Stack arrays in sequence horizontally (column wise)

a = np.array((1, 2, 3)) # rank-1 array (3, )
b = np.array((2, 3, 4)) # rank-1 array (3, )
print(np.hstack((a,b)))  # [1 2 3 2 3 4]

a = np.array([[1],[2],[3]]) # rank-2 array (3, 1)
b = np.array([[2],[3],[4]]) # rank-2 array (3, 1)
print(np.hstack((a,b)))  # [[1 2]
                         #  [2 3]
                         #  [3 4]]

[1 2 3 2 3 4]
[[1 2]
 [2 3]
 [3 4]]


<a id="section_5"></a>

## Constants

In [78]:
#IEEE 754 floating point representation of (positive) infinity.
np.inf

inf

In [79]:
#NumPy uses the IEEE Standard for Binary Floating-Point for Arithmetic (IEEE 754). 
#This means that Not a Number is not equivalent to infinity.
np.nan

nan

<a id="section_6"></a>

## Linear Algebra

In [80]:
#Computing the determinant of a square matrix
x = np.array([[1, 2], [3, 4]])
print(np.linalg.det(x))

-2.0


In [81]:
#Solving a linear matrix equation, or system of linear scalar equations Ax = b
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
print(x)

[ 2.  3.]


#### Note : Difference between (Moore-Penrose) pseudo-inverse `np.linalg.pinv` and inverse `np.linalg.inv` of a matrix 

If the determinant of the matrix is zero, it will not have an inverse and your `np.linalg.inv` function will not work. This usually happens if your matrix is singular. 

`np.linalg.pinv` will compute the inverse irrespective of whether the matrix is singular or not. This is because pinv returns the inverse of your matrix when it is available and the pseudo inverse when it isn't. It is recommended to use `pinv` instead of `inv`

In [82]:
#Compute the Moore-Penrose pseudo-inverse of a matrix
x = np.matrix([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

print(np.linalg.pinv(x))   # [[ -6.38888889e-01  -1.66666667e-01   3.05555556e-01]
                           #  [ -5.55555556e-02   1.59594560e-16   5.55555556e-02]
                           #  [  5.27777778e-01   1.66666667e-01  -1.94444444e-01]]

print()
#We can also calculate the inverse of a matrix
print(np.linalg.inv(x))    # [[  3.15251974e+15  -6.30503948e+15   3.15251974e+15]
                           #  [ -6.30503948e+15   1.26100790e+16  -6.30503948e+15]
                           #  [  3.15251974e+15  -6.30503948e+15   3.15251974e+15]]

[[ -6.38888889e-01  -1.66666667e-01   3.05555556e-01]
 [ -5.55555556e-02   1.59594560e-16   5.55555556e-02]
 [  5.27777778e-01   1.66666667e-01  -1.94444444e-01]]

[[  3.15251974e+15  -6.30503948e+15   3.15251974e+15]
 [ -6.30503948e+15   1.26100790e+16  -6.30503948e+15]
 [  3.15251974e+15  -6.30503948e+15   3.15251974e+15]]


In [83]:
#Compute the eigenvalues and right eigenvectors of a square array.
w, v = np.linalg.eig(np.diag((1, 2, 3)))

# Eigen values
print(w) # [ 1.  2.  3.]

print()

# Eigen vectors
print(v) # [[ 1.  0.  0.]
         #  [ 0.  1.  0.]
         #  [ 0.  0.  1.]]

[ 1.  2.  3.]

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [14]:
# Singular Value Decomposition

# Factors the matrix a as u * np.diag(s) * v, where u and v are unitary and s is a 1-d array of a‘s singular values.

# u, Unitary matrices. The actual shape depends on the value of full_matrices. Only returned when compute_uv is True.

# s, The singular values for every matrix, sorted in descending order.

# v, Unitary matrices. The actual shape depends on the value of full_matrices. Only returned when compute_uv is True.

x = np.random.randn(9, 6) + 1j*np.random.randn(9, 6)
U, s, V = np.linalg.svd(x, full_matrices=True)

## References

http://cs231n.github.io/python-numpy-tutorial/#numpy-arrays

https://docs.scipy.org/doc/numpy/reference/routines.math.html